//! Embeds everything under `static/` into the binary at compile time.
//!
//! Generates `$OUT_DIR/assets.rs` — a `(relative_path, bytes)` table built from
//! whatever files live under `static/`. Adding a file (or pointing `static/` at
//! a built frontend's output, e.g. a Vite `dist/`) embeds it automatically, with
//! no Rust changes and no extra dependency. Keeps the single-binary / offline
//! property: nothing is read from disk at runtime.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let static_dir = PathBuf::from(&manifest).join("static");
    println!("cargo:rerun-if-changed={}", static_dir.display());

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    collect(&static_dir, &static_dir, &mut files);
    files.sort();

    let mut out = String::from("// @generated by build.rs — embedded static assets.\n");
    out.push_str("pub static ASSETS: &[(&str, &[u8])] = &[\n");
    for (rel, abs) in &files {
        println!("cargo:rerun-if-changed={}", abs.display());
        out.push_str(&format!("    ({rel:?}, include_bytes!({abs:?})),\n"));
    }
    out.push_str("];\n");

    let out_path = Path::new(&std::env::var("OUT_DIR").unwrap()).join("assets.rs");
    fs::write(out_path, out).unwrap();
}

/// Recursively collects files as (path relative to `root`, absolute path).
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    for entry in fs::read_dir(dir).unwrap() {
        let path = entry.unwrap().path();
        if path.is_dir() {
            collect(root, &path, out);
        } else {
            let rel = path
                .strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/");
            out.push((rel, path));
        }
    }
}
