[package]
name = "hermione-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "hermione-server"
path = "src/main.rs"

[dependencies]
hermione-proto.workspace = true
hermione-entity.workspace = true
hermione-migration.workspace = true

tokio.workspace = true
tokio-stream.workspace = true
futures.workspace = true
async-stream.workspace = true

tonic.workspace = true
prost.workspace = true

axum.workspace = true
tower-http.workspace = true

sea-orm.workspace = true

anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
chrono.workspace = true
base64.workspace = true
strip-ansi-escapes.workspace = true
argon2.workspace = true
jsonwebtoken.workspace = true
reqwest.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }

[lints]
workspace = true
